"use strict";
exports.__esModule = true;
exports.syncShowAlert = exports.syncShowOk = exports.syncShape = exports.syncImage = exports.syncLabel = exports.syncPage = exports.dynamicBoard = exports.useEffect = exports.useState = exports.Hyper = exports.Quantum = void 0;
var Quantum = require("./quantum");
exports.Quantum = Quantum;
var hyper_1 = require("./hyper");
exports.Hyper = hyper_1["default"];
var hyper_hooks_1 = require("./hyper.hooks");
exports.useState = hyper_hooks_1.useState;
exports.useEffect = hyper_hooks_1.useEffect;
exports.dynamicBoard = hyper_hooks_1.dynamicBoard;
exports.syncPage = hyper_hooks_1.syncPage;
exports.syncLabel = hyper_hooks_1.syncLabel;
